In [4]:
import pandas as pd
df=pd.read_csv(r"C:\Users\neeth\Downloads\archive\student_exam_performance.csv")
df.head()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low

In [5]:
df.head()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low

In [6]:
df.tail()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
99995,STU_099996,17,Male,Undergraduate,Public,Upper-Middle,NaN,Suburban,78.73,NaN,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99996,STU_099997,14,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,...,Easy,24,94,91,84.29,8.68,96.54,A,Pass,High
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,STU_100000,18,Female,Undergraduate,Charter,Lower-Middle,NaN,Urban,76.73,2.97,...,Medium,1,92,52,NaN,10.00,54.40,D,Pass,Low

In [8]:
df.shape

(100000, 44)

In [9]:
df.columns

Index(['student_id', 'age', 'gender', 'education_level', 'school_type',
       'family_income', 'parent_education', 'urban_rural',
       'previous_exam_score', 'previous_gpa', 'attendance_percentage',
       'assignment_completion_rate', 'class_participation',
       'study_hours_per_day', 'self_study_hours', 'private_tuition',
       'online_learning_hours', 'study_consistency', 'study_environment',
       'study_method', 'revision_frequency', 'practice_tests_completed',
       'notes_quality', 'sleep_hours', 'sleep_quality', 'daily_screen_time',
       'physical_activity_hours', 'break_frequency', 'stress_level',
       'motivation_level', 'internet_access', 'device_availability',
       'educational_app_usage', 'online_course_hours', 'exam_difficulty',
       'exam_preparation_days', 'questions_attempted', 'questions_correct',
       'time_management_score', 'exam_anxiety_level', 'exam_score',
       'performance_grade', 'pass_status', 'performance_level'],
      dtype='str')

In [10]:
df.dtypes

student_id                        str
age                             int64
gender                            str
education_level                   str
school_type                       str
family_income                     str
parent_education                  str
urban_rural                       str
previous_exam_score           float64
previous_gpa                  float64
attendance_percentage         float64
assignment_completion_rate    float64
class_participation               str
study_hours_per_day           float64
self_study_hours              float64
private_tuition                 int64
online_learning_hours         float64
study_consistency                 str
study_environment                 str
study_method                      str
revision_frequency                str
practice_tests_completed        int64
notes_quality                     str
sleep_hours                   float64
sleep_quality                     str
daily_screen_time             float64
physical_activity_hours       float64
break_frequency                   str
stress_level                    int64
motivation_level                  str
internet_access                 int64
device_availability               str
educational_app_usage             str
online_course_hours           float64
exam_difficulty                   str
exam_preparation_days           int64
questions_attempted             int64
questions_correct               int64
time_management_score         float64
exam_anxiety_level            float64
exam_score                    float64
performance_grade                 str
pass_status                       str
performance_level                 str
dtype: object

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 44 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   student_id                  100000 non-null  str
 1   age                         100000 non-null  int64
 2   gender                      100000 non-null  str
 3   education_level             100000 non-null  str
 4   school_type                 100000 non-null  str
 5   family_income               100000 non-null  str
 6   parent_education            93474 non-null   str
 7   urban_rural                 100000 non-null  str
 8   previous_exam_score         100000 non-null  float64
 9   previous_gpa                92207 non-null   float64
 10  attendance_percentage       90137 non-null   float64
 11  assignment_completion_rate  100000 non-null  float64
 12  class_participation         100000 non-null  str
 13  study_hours_per_day         100000 non-null  float64
 14  self_study_hours            100000 non-null  float64
 15  private_tuition             100000 non-null  int64
 16  online_learning_hours       100000 non-null  float64
 17  study_consistency           100000 non-null  str
 18  study_environment           100000 non-null  str
 19  study_method                100000 non-null  str
 20  revision_frequency          100000 non-null  str
 21  practice_tests_completed    100000 non-null  int64
 22  notes_quality               91593 non-null   str
 23  sleep_hours                 100000 non-null  float64
 24  sleep_quality               93006 non-null   str
 25  daily_screen_time           100000 non-null  float64
 26  physical_activity_hours     100000 non-null  float64
 27  break_frequency             100000 non-null  str
 28  stress_level                100000 non-null  int64
 29  motivation_level            100000 non-null  str
 30  internet_access             100000 non-null  int64
 31  device_availability         97035 non-null   str
 32  educational_app_usage       100000 non-null  str
 33  online_course_hours         100000 non-null  float64
 34  exam_difficulty             100000 non-null  str
 35  exam_preparation_days       100000 non-null  int64
 36  questions_attempted         100000 non-null  int64
 37  questions_correct           100000 non-null  int64
 38  time_management_score       90387 non-null   float64
 39  exam_anxiety_level          100000 non-null  float64
 40  exam_score                  100000 non-null  float64
 41  performance_grade           100000 non-null  str
 42  pass_status                 100000 non-null  str
 43  performance_level           100000 non-null  str
dtypes: float64(14), int64(8), str(22)
memory usage: 33.6 MB

In [12]:
df.describe()

,age,previous_exam_score,previous_gpa,attendance_percentage,assignment_completion_rate,study_hours_per_day,self_study_hours,private_tuition,online_learning_hours,practice_tests_completed,...,physical_activity_hours,stress_level,internet_access,online_course_hours,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score
count,100000.000000,100000.000000,92207.000000,90137.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,90387.000000,100000.000000,100000.000000
mean,17.005740,69.531033,2.780892,84.616882,69.724405,2.995725,2.094970,0.299800,2.004763,5.509170,...,2.487579,9.375640,0.918760,2.999453,15.501440,92.492150,57.298240,78.398551,8.927373,61.950072
std,1.999562,11.379108,0.478218,7.922485,12.127179,1.719466,1.266066,0.458173,2.005719,2.501131,...,2.413386,1.081613,0.273205,2.983732,8.644356,4.609376,15.028787,14.105155,1.354875,15.863644
min,14.000000,30.000000,1.000000,46.340000,20.000000,0.500000,0.250000,0.000000,0.000000,0.000000,...,0.000000,5.000000,0.000000,0.000000,1.000000,85.000000,0.000000,17.030000,1.000000,0.000000
25%,15.000000,61.820000,2.460000,79.210000,61.480000,1.720000,1.170000,0.000000,0.580000,4.000000,...,0.720000,9.000000,1.000000,0.860000,8.000000,88.000000,47.000000,68.790000,8.220000,51.240000
50%,17.000000,69.530000,2.780000,84.750000,69.570000,2.670000,1.840000,0.000000,1.380000,5.000000,...,1.730000,10.000000,1.000000,2.080000,16.000000,92.000000,57.000000,79.000000,9.490000,61.960000
75%,19.000000,77.232500,3.110000,90.170000,77.920000,3.910000,2.730000,1.000000,2.770000,7.000000,...,3.480000,10.000000,1.000000,4.150000,23.000000,96.000000,67.000000,89.210000,10.000000,72.730000
max,20.000000,100.000000,4.000000,100.000000,100.000000,12.000000,10.000000,1.000000,15.000000,20.000000,...,12.000000,10.000000,1.000000,20.000000,30.000000,100.000000,100.000000,100.000000,10.000000,100.000000

In [14]:
df["age"].mean()

np.float64(17.00574)

In [15]:
df["age"].median()

np.float64(17.0)

In [16]:
df["age"].mode

<bound method Series.mode of 0        20
1        17
2        18
3        20
4        16
         ..
99995    17
99996    14
99997    16
99998    15
99999    18
Name: age, Length: 100000, dtype: int64>

In [18]:
df["age"].var()

np.float64(3.9982470348703485)

In [19]:
df["age"].std()

np.float64(1.999561710693208)

In [20]:
df["age"].min()

np.int64(14)

In [21]:
df["age"].max()

np.int64(20)

In [22]:
df["age"].count()

np.int64(100000)

In [25]:
df.isnull()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,False,False,False,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,False,False,False
99996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99999,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [26]:
df.isnull().sum()

student_id                       0
age                              0
gender                           0
education_level                  0
school_type                      0
family_income                    0
parent_education              6526
urban_rural                      0
previous_exam_score              0
previous_gpa                  7793
attendance_percentage         9863
assignment_completion_rate       0
class_participation              0
study_hours_per_day              0
self_study_hours                 0
private_tuition                  0
online_learning_hours            0
study_consistency                0
study_environment                0
study_method                     0
revision_frequency               0
practice_tests_completed         0
notes_quality                 8407
sleep_hours                      0
sleep_quality                 6994
daily_screen_time                0
physical_activity_hours          0
break_frequency                  0
stress_level                     0
motivation_level                 0
internet_access                  0
device_availability           2965
educational_app_usage            0
online_course_hours              0
exam_difficulty                  0
exam_preparation_days            0
questions_attempted              0
questions_correct                0
time_management_score         9613
exam_anxiety_level               0
exam_score                       0
performance_grade                0
pass_status                      0
performance_level                0
dtype: int64

In [27]:
df.isnull().mean()*100

student_id                    0.000
age                           0.000
gender                        0.000
education_level               0.000
school_type                   0.000
family_income                 0.000
parent_education              6.526
urban_rural                   0.000
previous_exam_score           0.000
previous_gpa                  7.793
attendance_percentage         9.863
assignment_completion_rate    0.000
class_participation           0.000
study_hours_per_day           0.000
self_study_hours              0.000
private_tuition               0.000
online_learning_hours         0.000
study_consistency             0.000
study_environment             0.000
study_method                  0.000
revision_frequency            0.000
practice_tests_completed      0.000
notes_quality                 8.407
sleep_hours                   0.000
sleep_quality                 6.994
daily_screen_time             0.000
physical_activity_hours       0.000
break_frequency               0.000
stress_level                  0.000
motivation_level              0.000
internet_access               0.000
device_availability           2.965
educational_app_usage         0.000
online_course_hours           0.000
exam_difficulty               0.000
exam_preparation_days         0.000
questions_attempted           0.000
questions_correct             0.000
time_management_score         9.613
exam_anxiety_level            0.000
exam_score                    0.000
performance_grade             0.000
pass_status                   0.000
performance_level             0.000
dtype: float64

In [28]:
df.dropna()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
7,STU_000008,20,Female,Undergraduate,Private,Lower-Middle,Bachelor,Suburban,90.79,3.63,...,Easy,7,94,91,88.08,10.00,97.61,A,Pass,High
8,STU_000009,15,Male,Undergraduate,Public,Lower-Middle,Associate,Suburban,61.28,2.43,...,Hard,14,94,35,70.21,8.34,34.44,F,Fail,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,STU_099992,19,Female,Undergraduate,Public,Upper-Middle,Master,Suburban,72.32,3.05,...,Medium,3,97,63,75.44,7.32,61.12,D,Pass,Medium
99992,STU_099993,19,Female,High School,Public,Low,High School,Urban,67.13,2.37,...,Easy,29,94,65,98.67,10.00,67.74,C,Pass,Medium
99994,STU_099995,15,Male,High School,Public,Low,Associate,Urban,54.37,2.13,...,Easy,5,97,39,79.83,10.00,40.70,F,Fail,Low
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High

In [29]:
df.fillna(0)

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,0,Rural,78.36,2.95,...,Medium,27,95,86,0.00,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,0,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,STU_099996,17,Male,Undergraduate,Public,Upper-Middle,0,Suburban,78.73,0.00,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99996,STU_099997,14,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,...,Easy,24,94,91,84.29,8.68,96.54,A,Pass,High
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,STU_100000,18,Female,Undergraduate,Charter,Lower-Middle,0,Urban,76.73,2.97,...,Medium,1,92,52,0.00,10.00,54.40,D,Pass,Low

In [30]:
df.duplicated

<bound method DataFrame.duplicated of        student_id  age  gender education_level school_type family_income  \
0      STU_000001   20  Female     High School      Public        Middle
1      STU_000002   17    Male     High School      Public        Middle
2      STU_000003   18   Other   Undergraduate      Public        Middle
3      STU_000004   20    Male     High School      Public        Middle
4      STU_000005   16  Female     High School     Private          High
...           ...  ...     ...             ...         ...           ...
99995  STU_099996   17    Male   Undergraduate      Public  Upper-Middle
99996  STU_099997   14  Female     High School      Public  Upper-Middle
99997  STU_099998   16  Female     High School      Public  Upper-Middle
99998  STU_099999   15  Female     High School     Private          High
99999  STU_100000   18  Female   Undergraduate     Charter  Lower-Middle

      parent_education urban_rural  previous_exam_score  previous_gpa  ...  \
0                  NaN       Rural                78.36          2.95  ...
1                  NaN    Suburban                73.40          2.89  ...
2               Master       Urban                82.76          3.35  ...
3          High School    Suburban                60.61          2.57  ...
4             Bachelor    Suburban                74.79          2.84  ...
...                ...         ...                  ...           ...  ...
99995              NaN    Suburban                78.73           NaN  ...
99996         Bachelor    Suburban                75.70          2.98  ...
99997      High School    Suburban                84.69          3.27  ...
99998           Master       Rural                74.70          3.06  ...
99999              NaN       Urban                76.73          2.97  ...

       exam_difficulty  exam_preparation_days questions_attempted  \
0               Medium                     27                  95
1                 Easy                      4                 100
2                 Easy                     28                  96
3               Medium                     16                  97
4               Medium                     28                  98
...                ...                    ...                 ...
99995           Medium                      5                  95
99996             Easy                     24                  94
99997           Medium                     24                  85
99998           Medium                     28                  93
99999           Medium                      1                  92

       questions_correct  time_management_score  exam_anxiety_level  \
0                     86                    NaN                9.39
1                     86                  87.17                6.31
2                     74                  63.77                9.87
3                     77                  59.51                9.68
4                     52                  84.64               10.00
...                  ...                    ...                 ...
99995                 62                  76.13                8.36
99996                 91                  84.29                8.68
99997                 65                  62.32                9.97
99998                 81                 100.00               10.00
99999                 52                    NaN               10.00

       exam_score performance_grade pass_status performance_level
0           90.40                 A        Pass              High
1           86.21                 A        Pass              High
2           76.11                 B        Pass            Medium
3           79.74                 B        Pass            Medium
4           50.66                 D        Pass               Low
...           ...               ...         ...               ...
99995       66.46                 C        Pass            Medium
99996       96.54                 A        Pass              High
99997       74.66                 C        Pass            Medium
99998       85.85                 A        Pass              High
99999       54.40                 D        Pass               Low

[100000 rows x 44 columns]>

In [31]:
df.duplicated().sum()

np.int64(0)

In [32]:
df.drop_duplicates()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,STU_099996,17,Male,Undergraduate,Public,Upper-Middle,NaN,Suburban,78.73,NaN,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99996,STU_099997,14,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,...,Easy,24,94,91,84.29,8.68,96.54,A,Pass,High
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,STU_100000,18,Female,Undergraduate,Charter,Lower-Middle,NaN,Urban,76.73,2.97,...,Medium,1,92,52,NaN,10.00,54.40,D,Pass,Low

In [33]:
df["age"]

0        20
1        17
2        18
3        20
4        16
         ..
99995    17
99996    14
99997    16
99998    15
99999    18
Name: age, Length: 100000, dtype: int64

In [34]:
df.iloc[0:5]

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low

In [36]:
df[["age","exam_score"]]

       age  exam_score
0       20       90.40
1       17       86.21
2       18       76.11
3       20       79.74
4       16       50.66
...    ...         ...
99995   17       66.46
99996   14       96.54
99997   16       74.66
99998   15       85.85
99999   18       54.40

[100000 rows x 2 columns]

In [37]:
df[df["age"] > 30]

Empty DataFrame
Columns: [student_id, age, gender, education_level, school_type, family_income, parent_education, urban_rural, previous_exam_score, previous_gpa, attendance_percentage, assignment_completion_rate, class_participation, study_hours_per_day, self_study_hours, private_tuition, online_learning_hours, study_consistency, study_environment, study_method, revision_frequency, practice_tests_completed, notes_quality, sleep_hours, sleep_quality, daily_screen_time, physical_activity_hours, break_frequency, stress_level, motivation_level, internet_access, device_availability, educational_app_usage, online_course_hours, exam_difficulty, exam_preparation_days, questions_attempted, questions_correct, time_management_score, exam_anxiety_level, exam_score, performance_grade, pass_status, performance_level]
Index: []

[0 rows x 44 columns]

In [38]:
df.sort_values("age")

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
58,STU_000059,14,Male,Undergraduate,Private,Lower-Middle,High School,Rural,67.59,2.96,...,Medium,3,95,66,100.00,9.23,72.53,C,Pass,Medium
63,STU_000064,14,Female,Undergraduate,Public,Lower-Middle,Associate,Urban,58.77,2.08,...,Hard,23,99,78,74.58,8.86,79.10,B,Pass,Medium
71314,STU_071315,14,Female,Undergraduate,Public,Lower-Middle,Master,Urban,57.96,2.41,...,Easy,21,99,66,61.86,9.14,67.94,C,Pass,Medium
71323,STU_071324,14,Male,Undergraduate,Public,Middle,High School,Suburban,81.30,3.28,...,Medium,27,88,54,79.81,10.00,64.20,D,Pass,Medium
71324,STU_071325,14,Male,High School,Private,Middle,NaN,Rural,79.58,3.17,...,Medium,17,92,79,74.55,10.00,89.13,A,Pass,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71341,STU_071342,20,Male,Undergraduate,Private,Middle,Associate,Urban,66.00,2.70,...,Hard,16,100,75,71.62,6.58,75.55,B,Pass,Medium
71340,STU_071341,20,Male,High School,Private,High,High School,Rural,63.60,2.52,...,Medium,12,93,54,80.89,10.00,56.90,D,Pass,Low
46,STU_000047,20,Female,High School,Public,Middle,Master,Rural,81.12,3.34,...,Hard,3,91,64,73.60,9.50,70.64,C,Pass,Medium
71321,STU_071322,20,Female,Undergraduate,Public,Low,Bachelor,Urban,75.34,3.17,...,Easy,28,88,78,65.48,8.15,86.81,A,Pass,High
71338,STU_071339,20,Female,Undergraduate,Private,Lower-Middle,High School,Suburban,59.23,2.44,...,Hard,16,90,42,75.44,9.97,47.87,F,Fail,Low

In [39]:
df.rename(columns={"age":"age_Years"})

,student_id,age_Years,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,STU_099996,17,Male,Undergraduate,Public,Upper-Middle,NaN,Suburban,78.73,NaN,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99996,STU_099997,14,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,...,Easy,24,94,91,84.29,8.68,96.54,A,Pass,High
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,STU_100000,18,Female,Undergraduate,Charter,Lower-Middle,NaN,Urban,76.73,2.97,...,Medium,1,92,52,NaN,10.00,54.40,D,Pass,Low

In [44]:


df.drop("Bonus", axis=1)

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,STU_099996,17,Male,Undergraduate,Public,Upper-Middle,NaN,Suburban,78.73,NaN,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99996,STU_099997,14,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,...,Easy,24,94,91,84.29,8.68,96.54,A,Pass,High
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,STU_100000,18,Female,Undergraduate,Charter,Lower-Middle,NaN,Urban,76.73,2.97,...,Medium,1,92,52,NaN,10.00,54.40,D,Pass,Low